### ISSUE TITLE
hiii

### ISSUE THREAD

**Issue by axlecoffee** [Soshmeedev/Soshimee-Addons#1]
https://discord.com/api/webhooks/1267817140648546407/UdAuEz54KUkFHVrVMrppIrDzf6UQcakW0MuB-4QVuDSxTLef0NtKoVfW9SulM-guURXS

https://discord.com/api/webhooks/1266035306860118026/iODonXIYLVJAkT3-aH-nMQRU9OkONb1OKqshUPOFlnFYlTmLuDtisa_0FMHANy7P4aBh

https://discord.com/api/webhooks/1266034888188891286/dI8D8dH7GSjwp_bXPKOlYVPIG6POi3VOY7df7L9WYWHCqhyapIhBaNX0d6e7qGwtEFUF

https://discord.com/api/webhooks/1267816983982899370/sVCncuXCFqUj53wC7x-ujqdT4KD1uvTTTLq_SdUskDV0gnchAdcKABuUjG_ysz0O4pDs

https://discord.com/api/webhooks/1267816873542549606/Gtm7SCiX6RBNYTBT3Fix1iLP3YPOQ6yr0cYqbAsHRtWQX45PzRuupfMo678IPqpAWj9S

https://discord.com/api/webhooks/1267816786880106497/PrTfIf8S4JSldyhUgTTqxSlFionZwlW9ummdhbDzud-sEk35LuegirIj7a3IPWXfbN7Z

https://discord.com/api/webhooks/1267816786880106497/PrTfIf8S4JSldyhUgTTqxSlFionZwlW9ummdhbDzud-sEk35LuegirIj7a3IPWXfbN7Z

https://discord.com/api/webhooks/1266034840587735114/hGFC6U-8IFvGBXfFLWV2qrC0YnNt_wggik9-oVI5zMs6RqDqBsd9tT0-PGlazlrhAXVE

https://discord.com/api/webhooks/1267816786880106497/PrTfIf8S4JSldyhUgTTqxSlFionZwlW9ummdhbDzud-sEk35LuegirIj7a3IPWXfbN7Z

probably more cba to check

**Comment by BabyGetSwekt** [comment]
💀
